### ISSUE TITLE
MVP suggestions

### ISSUE THREAD

**Issue by snide** [elastic/gatsby-eui-starter#2]
Tried this out tonight. Before you go too deep, I think you want the following in here at a minimum.

1. Should probably use TypeScript since that's the direction everything is going and the last thing we want to do is convert it later.
2. We should prolly get the breadcrumbs working with the routing somehow.
3. Need a very minimum way to quickly deploy to GH pages.

Since this will be a public repo I think you want to be specific with naming. There's nothing Kibana in here, it's just loading EUI and I wouldn't want people confused of its intention. Likely `gatsby-eui-starter` makes more sense.

I can help out. I think this is really cool and we'd use it all the time.

**Comment by thompsongl** [comment]
+1 for `gatsby-eui-starter`. Possibly even swapping the Kibana logo for Elastic's (or whatever).

I'm happy to help out with whatever

**Comment by snide** [comment]
All of this has been done. The breadcrumbs can be handled manually for the moment.
